name: First example
on:
  push:
    branches:
      - master
  # 当有分支合并到master时，会触发actions
  pull-request:
    branches: [master]
jobs:
  hello-actions:
    runs-on: ubuntu-18.04
    name: hello-actions
    steps:
      # 每一个步骤跟随一个 name ，还有一些其他的参数。
      - name: Checkout Master
        uses: actions/checkout@v1

      - name: Cat text
        run: |
          cat text.txt

      - name: Connect Baidu
        run: curl 'http://www.baidu.com'
  
